#include <gtest/gtest.h>

#include "engine/engine.hpp"
#include "engine/core/logger.hpp"
#include "engine/core/ecs.hpp"
#include "engine/core/components/transform.hpp"
#include "engine/tools/fmt_defines.hpp"

/* ! Generated by AI ! */

// ==================== Helper Functions ====================
bool approx_equal(float a, float b, float epsilon = 0.0001f) { return std::abs(a - b) < epsilon; }

bool vec3_approx_equal(const glm::vec3& a, const glm::vec3& b, float epsilon = 0.0001f) {
    return approx_equal(a.x, b.x, epsilon) && approx_equal(a.y, b.y, epsilon) && approx_equal(a.z, b.z, epsilon);
}

bool quat_approx_equal(const glm::quat& a, const glm::quat& b, float epsilon = 0.0001f) {
    bool same = approx_equal(a.w, b.w, epsilon) && approx_equal(a.x, b.x, epsilon) && approx_equal(a.y, b.y, epsilon) && approx_equal(a.z, b.z, epsilon);

    bool opposite = approx_equal(a.w, -b.w, epsilon) && approx_equal(a.x, -b.x, epsilon) && approx_equal(a.y, -b.y, epsilon) && approx_equal(a.z, -b.z, epsilon);

    return same || opposite;
}

// ==================== Test Fixture ====================
class TransformTest : public ::testing::Test {
   protected:
    void SetUp() override {
        // Initialize engine if needed
        // static bool engine_initialized = false;
        // if (!engine_initialized) {
        //    tmt::ApplicationSpecs specs {.name = "Transform Tests", .command_args = {0, nullptr}};
        //    tmt::engine.init(specs);
        //    engine_initialized = true;
        //}
    }

    void TearDown() override { tmt::engine.ecs.clear(); }
};

// ==================== Local Position Tests ====================
TEST_F(TransformTest, LocalPositionGetterSetter) {
    tmt::Entity entity = tmt::engine.ecs.create_entity();
    auto& transform = tmt::engine.ecs.add_component<tmt::Transform>(entity);

    // Default position
    EXPECT_TRUE(vec3_approx_equal(transform.get_local_position(), glm::vec3(0.0f)));

    // Set and get position
    glm::vec3 pos(1.0f, 2.0f, 3.0f);
    transform.set_local_position(pos);
    EXPECT_TRUE(vec3_approx_equal(transform.get_local_position(), pos));

    // Edge case: negative values
    pos = glm::vec3(-5.0f, -10.0f, -15.0f);
    transform.set_local_position(pos);
    EXPECT_TRUE(vec3_approx_equal(transform.get_local_position(), pos));

    // Edge case: very large values
    pos = glm::vec3(1000000.0f, 2000000.0f, 3000000.0f);
    transform.set_local_position(pos);
    EXPECT_TRUE(vec3_approx_equal(transform.get_local_position(), pos));

    // Edge case: very small values
    pos = glm::vec3(0.0001f, 0.0002f, 0.0003f);
    transform.set_local_position(pos);
    EXPECT_TRUE(vec3_approx_equal(transform.get_local_position(), pos));
}

// ==================== Local Rotation Tests ====================
TEST_F(TransformTest, LocalRotationQuaternion) {
    tmt::Entity entity = tmt::engine.ecs.create_entity();
    auto& transform = tmt::engine.ecs.add_component<tmt::Transform>(entity);

    // Default rotation (identity)
    EXPECT_TRUE(quat_approx_equal(transform.get_local_rotation(), glm::quat(1.0f, 0.0f, 0.0f, 0.0f)));

    // Set rotation
    glm::quat rot = glm::angleAxis(glm::radians(45.0f), glm::vec3(0.0f, 1.0f, 0.0f));
    transform.set_local_rotation(rot);
    EXPECT_TRUE(quat_approx_equal(transform.get_local_rotation(), rot));

    // Edge case: 180 degree rotation
    rot = glm::angleAxis(glm::radians(180.0f), glm::vec3(1.0f, 0.0f, 0.0f));
    transform.set_local_rotation(rot);
    EXPECT_TRUE(quat_approx_equal(transform.get_local_rotation(), rot));

    // Edge case: identity quaternion
    rot = glm::quat(1.0f, 0.0f, 0.0f, 0.0f);
    transform.set_local_rotation(rot);
    EXPECT_TRUE(quat_approx_equal(transform.get_local_rotation(), rot));
}

TEST_F(TransformTest, LocalRotationEuler) {
    tmt::Entity entity = tmt::engine.ecs.create_entity();
    auto& transform = tmt::engine.ecs.add_component<tmt::Transform>(entity);

    // Zero euler angles
    glm::vec3 euler(0.0f, 0.0f, 0.0f);
    transform.set_local_rotation(euler);
    EXPECT_TRUE(quat_approx_equal(transform.get_local_rotation(), glm::quat(1.0f, 0.0f, 0.0f, 0.0f)));

    // Set euler angles (45 degrees on each axis)
    euler = glm::vec3(glm::radians(45.0f), glm::radians(45.0f), glm::radians(45.0f));
    transform.set_local_rotation(euler);
    auto expected = glm::quat(euler);
    EXPECT_TRUE(quat_approx_equal(transform.get_local_rotation(), expected));

    // Edge case: 90 degree pitch (potential gimbal lock)
    euler = glm::vec3(glm::radians(90.0f), 0.0f, 0.0f);
    transform.set_local_rotation(euler);
    expected = glm::quat(euler);
    EXPECT_TRUE(quat_approx_equal(transform.get_local_rotation(), expected));

    // Edge case: negative angles
    euler = glm::vec3(glm::radians(-30.0f), glm::radians(-60.0f), glm::radians(-90.0f));
    transform.set_local_rotation(euler);
    expected = glm::quat(euler);
    EXPECT_TRUE(quat_approx_equal(transform.get_local_rotation(), expected));
}

TEST_F(TransformTest, LocalRotationAxisAngle) {
    tmt::Entity entity = tmt::engine.ecs.create_entity();
    auto& transform = tmt::engine.ecs.add_component<tmt::Transform>(entity);

    // 90 degrees around Y axis
    glm::vec3 axis(0.0f, 1.0f, 0.0f);
    float angle = glm::radians(90.0f);
    transform.set_local_rotation(axis, angle);
    glm::quat expected = glm::angleAxis(angle, axis);
    EXPECT_TRUE(quat_approx_equal(transform.get_local_rotation(), expected));

    // Edge case: zero angle
    transform.set_local_rotation(axis, 0.0f);
    EXPECT_TRUE(quat_approx_equal(transform.get_local_rotation(), glm::quat(1.0f, 0.0f, 0.0f, 0.0f)));

    // Edge case: 360 degrees (should be identity)
    transform.set_local_rotation(axis, glm::radians(360.0f));
    EXPECT_TRUE(quat_approx_equal(transform.get_local_rotation(), glm::quat(1.0f, 0.0f, 0.0f, 0.0f)));

    // Edge case: arbitrary axis
    axis = glm::normalize(glm::vec3(1.0f, 2.0f, 3.0f));
    angle = glm::radians(120.0f);
    transform.set_local_rotation(axis, angle);
    expected = glm::angleAxis(angle, axis);
    EXPECT_TRUE(quat_approx_equal(transform.get_local_rotation(), expected));
}

// ==================== Local Scale Tests ====================
TEST_F(TransformTest, LocalScale) {
    tmt::Entity entity = tmt::engine.ecs.create_entity();
    auto& transform = tmt::engine.ecs.add_component<tmt::Transform>(entity);

    // Default scale
    EXPECT_TRUE(vec3_approx_equal(transform.get_local_scale(), glm::vec3(1.0f)));

    // Set non-uniform scale
    glm::vec3 scale(2.0f, 3.0f, 4.0f);
    transform.set_local_scale(scale);
    EXPECT_TRUE(vec3_approx_equal(transform.get_local_scale(), scale));

    // Edge case: zero scale (degenerate)
    scale = glm::vec3(0.0f);
    transform.set_local_scale(scale);
    EXPECT_TRUE(vec3_approx_equal(transform.get_local_scale(), scale));

    // Edge case: negative scale (mirroring)
    scale = glm::vec3(-1.0f, 1.0f, -1.0f);
    transform.set_local_scale(scale);
    EXPECT_TRUE(vec3_approx_equal(transform.get_local_scale(), scale));

    // Edge case: very large scale
    scale = glm::vec3(1000.0f, 2000.0f, 3000.0f);
    transform.set_local_scale(scale);
    EXPECT_TRUE(vec3_approx_equal(transform.get_local_scale(), scale));
}

// ==================== World Position Tests ====================
TEST_F(TransformTest, WorldPositionNoParent) {
    tmt::Entity entity = tmt::engine.ecs.create_entity();
    auto& transform = tmt::engine.ecs.add_component<tmt::Transform>(entity);

    // Without parent, world position should equal local position
    glm::vec3 pos(5.0f, 10.0f, 15.0f);
    transform.set_local_position(pos);
    EXPECT_TRUE(vec3_approx_equal(transform.get_world_position(), pos));

    // Set world position directly
    pos = glm::vec3(20.0f, 25.0f, 30.0f);
    transform.set_world_position(pos);
    EXPECT_TRUE(vec3_approx_equal(transform.get_world_position(), pos));
    EXPECT_TRUE(vec3_approx_equal(transform.get_local_position(), pos));
}

TEST_F(TransformTest, WorldPositionWithParent) {
    tmt::Entity parent_entity = tmt::engine.ecs.create_entity();
    tmt::Entity child_entity = tmt::engine.ecs.create_entity();

    auto& parent = tmt::engine.ecs.add_component<tmt::Transform>(parent_entity);
    auto& child = tmt::engine.ecs.add_component<tmt::Transform>(child_entity);

    // Set parent position
    parent.set_local_position(glm::vec3(10.0f, 20.0f, 30.0f));

    // Set child as child of parent
    child.set_parent(parent_entity);

    // Set child local position
    child.set_local_position(glm::vec3(5.0f, 5.0f, 5.0f));

    // World position should be parent + child
    glm::vec3 expected_world = glm::vec3(15.0f, 25.0f, 35.0f);
    EXPECT_TRUE(vec3_approx_equal(child.get_world_position(), expected_world));

    // Set world position of child
    child.set_world_position(glm::vec3(100.0f, 100.0f, 100.0f));
    EXPECT_TRUE(vec3_approx_equal(child.get_world_position(), glm::vec3(100.0f, 100.0f, 100.0f)));
}

// ==================== World Rotation Tests ====================
TEST_F(TransformTest, WorldRotationNoParent) {
    tmt::Entity entity = tmt::engine.ecs.create_entity();
    auto& transform = tmt::engine.ecs.add_component<tmt::Transform>(entity);

    // Without parent, world rotation should equal local rotation
    glm::quat rot = glm::angleAxis(glm::radians(45.0f), glm::vec3(0.0f, 1.0f, 0.0f));
    transform.set_local_rotation(rot);
    EXPECT_TRUE(quat_approx_equal(transform.get_world_rotation(), rot));

    // Set world rotation using euler angles
    glm::vec3 euler(glm::radians(30.0f), glm::radians(60.0f), glm::radians(90.0f));
    transform.set_world_rotation(euler);
    auto expected = glm::quat(euler);
    EXPECT_TRUE(quat_approx_equal(transform.get_world_rotation(), expected));

    // Set world rotation using axis-angle
    glm::vec3 axis = glm::normalize(glm::vec3(1.0f, 1.0f, 1.0f));
    float angle = glm::radians(60.0f);
    transform.set_world_rotation(axis, angle);
    expected = glm::angleAxis(angle, axis);
    EXPECT_TRUE(quat_approx_equal(transform.get_world_rotation(), expected));
}

// ==================== World Scale Tests ====================
TEST_F(TransformTest, WorldScaleNoParent) {
    tmt::Entity entity = tmt::engine.ecs.create_entity();
    auto& transform = tmt::engine.ecs.add_component<tmt::Transform>(entity);

    // Without parent, world scale should equal local scale
    glm::vec3 scale(2.0f, 3.0f, 4.0f);
    transform.set_local_scale(scale);
    EXPECT_TRUE(vec3_approx_equal(transform.get_world_scale(), scale));

    // Set world scale directly
    scale = glm::vec3(5.0f, 6.0f, 7.0f);
    transform.set_world_scale(scale);
    EXPECT_TRUE(vec3_approx_equal(transform.get_world_scale(), scale));
}

// ==================== Transform Operations Tests ====================
TEST_F(TransformTest, Translate) {
    tmt::Entity entity = tmt::engine.ecs.create_entity();
    auto& transform = tmt::engine.ecs.add_component<tmt::Transform>(entity);

    transform.set_local_position(glm::vec3(10.0f, 10.0f, 10.0f));

    // Translate by delta
    transform.translate(glm::vec3(5.0f, -3.0f, 2.0f));
    EXPECT_TRUE(vec3_approx_equal(transform.get_local_position(), glm::vec3(15.0f, 7.0f, 12.0f)));

    // Translate by zero
    transform.translate(glm::vec3(0.0f));
    EXPECT_TRUE(vec3_approx_equal(transform.get_local_position(), glm::vec3(15.0f, 7.0f, 12.0f)));

    // Multiple translations
    transform.translate(glm::vec3(1.0f, 1.0f, 1.0f));
    transform.translate(glm::vec3(2.0f, 2.0f, 2.0f));
    EXPECT_TRUE(vec3_approx_equal(transform.get_local_position(), glm::vec3(18.0f, 10.0f, 15.0f)));
}

TEST_F(TransformTest, RotateLocalQuaternion) {
    tmt::Entity entity = tmt::engine.ecs.create_entity();
    auto& transform = tmt::engine.ecs.add_component<tmt::Transform>(entity);

    // Start with identity
    glm::quat initial = glm::angleAxis(glm::radians(45.0f), glm::vec3(0.0f, 1.0f, 0.0f));
    transform.set_local_rotation(initial);

    // Rotate by additional amount
    glm::quat delta = glm::angleAxis(glm::radians(45.0f), glm::vec3(0.0f, 1.0f, 0.0f));
    transform.rotate_local(delta);

    glm::quat expected = delta * initial;
    EXPECT_TRUE(quat_approx_equal(transform.get_local_rotation(), expected));
}

TEST_F(TransformTest, RotateLocalEuler) {
    tmt::Entity entity = tmt::engine.ecs.create_entity();
    auto& transform = tmt::engine.ecs.add_component<tmt::Transform>(entity);

    glm::quat initial = glm::angleAxis(glm::radians(30.0f), glm::vec3(1.0f, 0.0f, 0.0f));
    transform.set_local_rotation(initial);

    // Rotate by euler angles
    glm::vec3 euler_delta(glm::radians(15.0f), glm::radians(30.0f), glm::radians(45.0f));
    transform.rotate_local(euler_delta);

    auto delta = glm::quat(euler_delta);
    auto expected = initial * delta;
    auto current = transform.get_local_rotation();
    EXPECT_TRUE(quat_approx_equal(current, expected));
}

TEST_F(TransformTest, RotateLocalAxisAngle) {
    tmt::Entity entity = tmt::engine.ecs.create_entity();
    auto& transform = tmt::engine.ecs.add_component<tmt::Transform>(entity);

    glm::quat initial = glm::angleAxis(glm::radians(60.0f), glm::vec3(0.0f, 0.0f, 1.0f));
    transform.set_local_rotation(initial);

    // Rotate around an axis
    glm::vec3 axis = glm::normalize(glm::vec3(1.0f, 1.0f, 0.0f));
    float angle = glm::radians(30.0f);
    transform.rotate_local(axis, angle);

    glm::quat delta = glm::angleAxis(angle, axis);
    glm::quat expected = initial * delta;
    EXPECT_TRUE(quat_approx_equal(transform.get_local_rotation(), expected));
}

TEST_F(TransformTest, RotateWorldQuaternion) {
    tmt::Entity entity = tmt::engine.ecs.create_entity();
    auto& transform = tmt::engine.ecs.add_component<tmt::Transform>(entity);

    glm::quat initial = glm::angleAxis(glm::radians(45.0f), glm::vec3(0.0f, 1.0f, 0.0f));
    transform.set_local_rotation(initial);

    // Rotate in world space
    glm::quat delta = glm::angleAxis(glm::radians(30.0f), glm::vec3(1.0f, 0.0f, 0.0f));
    transform.rotate_world(delta);

    glm::quat expected = delta * initial;
    EXPECT_TRUE(quat_approx_equal(transform.get_local_rotation(), expected));
}

TEST_F(TransformTest, RotateWorldEuler) {
    tmt::Entity entity = tmt::engine.ecs.create_entity();
    auto& transform = tmt::engine.ecs.add_component<tmt::Transform>(entity);

    glm::quat initial = glm::angleAxis(glm::radians(45.0f), glm::vec3(0.0f, 1.0f, 0.0f));
    transform.set_local_rotation(initial);

    glm::vec3 euler_delta(glm::radians(10.0f), glm::radians(20.0f), glm::radians(30.0f));
    transform.rotate_world(euler_delta);

    auto delta = glm::quat(euler_delta);
    auto expected = delta * initial;
    EXPECT_TRUE(quat_approx_equal(transform.get_local_rotation(), expected));
}

TEST_F(TransformTest, RotateWorldAxisAngle) {
    tmt::Entity entity = tmt::engine.ecs.create_entity();
    auto& transform = tmt::engine.ecs.add_component<tmt::Transform>(entity);

    glm::quat initial = glm::angleAxis(glm::radians(90.0f), glm::vec3(0.0f, 1.0f, 0.0f));
    transform.set_local_rotation(initial);

    glm::vec3 axis(0.0f, 0.0f, 1.0f);
    float angle = glm::radians(45.0f);
    transform.rotate_world(axis, angle);

    glm::quat delta = glm::angleAxis(angle, axis);
    glm::quat expected = delta * initial;
    EXPECT_TRUE(quat_approx_equal(transform.get_local_rotation(), expected));
}

TEST_F(TransformTest, Scale) {
    tmt::Entity entity = tmt::engine.ecs.create_entity();
    auto& transform = tmt::engine.ecs.add_component<tmt::Transform>(entity);

    transform.set_local_scale(glm::vec3(2.0f, 3.0f, 4.0f));

    // Scale by factor
    transform.scale(glm::vec3(2.0f, 0.5f, 3.0f));
    EXPECT_TRUE(vec3_approx_equal(transform.get_local_scale(), glm::vec3(4.0f, 1.5f, 12.0f)));

    // Scale by 1 (no change)
    transform.scale(glm::vec3(1.0f));
    EXPECT_TRUE(vec3_approx_equal(transform.get_local_scale(), glm::vec3(4.0f, 1.5f, 12.0f)));

    // Scale by zero (degenerate)
    transform.scale(glm::vec3(0.0f));
    EXPECT_TRUE(vec3_approx_equal(transform.get_local_scale(), glm::vec3(0.0f)));
}

// ==================== Direction Vector Tests ====================
TEST_F(TransformTest, ForwardUpRightVectors) {
    tmt::Entity entity = tmt::engine.ecs.create_entity();
    auto& transform = tmt::engine.ecs.add_component<tmt::Transform>(entity);

    // Identity rotation
    transform.set_local_rotation(glm::quat(1.0f, 0.0f, 0.0f, 0.0f));

    glm::vec3 forward = transform.get_forward();
    glm::vec3 up = transform.get_up();
    glm::vec3 right = transform.get_right();

    EXPECT_TRUE(vec3_approx_equal(forward, glm::vec3(0.0f, 0.0f, -1.0f), 0.01f));
    EXPECT_TRUE(vec3_approx_equal(up, glm::vec3(0.0f, 1.0f, 0.0f), 0.01f));
    EXPECT_TRUE(vec3_approx_equal(right, glm::vec3(1.0f, 0.0f, 0.0f), 0.01f));

    // Rotate 90 degrees around Y axis
    transform.set_local_rotation(glm::angleAxis(glm::radians(90.0f), glm::vec3(0.0f, 1.0f, 0.0f)));
    forward = transform.get_forward();
    right = transform.get_right();

    EXPECT_TRUE(vec3_approx_equal(forward, glm::vec3(-1.0f, 0.0f, 0.0f), 0.01f));
    EXPECT_TRUE(vec3_approx_equal(right, glm::vec3(0.0f, 0.0f, -1.0f), 0.01f));

    // Rotate 90 degrees around X axis
    transform.set_local_rotation(glm::angleAxis(glm::radians(90.0f), glm::vec3(1.0f, 0.0f, 0.0f)));
    forward = transform.get_forward();
    up = transform.get_up();

    EXPECT_TRUE(vec3_approx_equal(forward, glm::vec3(0.0f, 1.0f, 0.0f), 0.01f));
    EXPECT_TRUE(vec3_approx_equal(up, glm::vec3(0.0f, 0.0f, 1.0f), 0.01f));
}

TEST_F(TransformTest, LookAt) {
    tmt::Entity entity = tmt::engine.ecs.create_entity();
    auto& transform = tmt::engine.ecs.add_component<tmt::Transform>(entity);

    transform.set_local_position(glm::vec3(0.0f, 0.0f, 0.0f));

    // Look at target directly ahead
    glm::vec3 target(0.0f, 0.0f, -10.0f);
    glm::vec3 up(0.0f, 1.0f, 0.0f);
    transform.look_at(target, up);

    glm::vec3 forward = transform.get_forward();
    glm::vec3 expected_dir = glm::normalize(target - transform.get_local_position());
    EXPECT_TRUE(vec3_approx_equal(forward, expected_dir, 0.01f));

    // Look at target to the right
    target = glm::vec3(10.0f, 0.0f, 0.0f);
    transform.look_at(target, up);
    forward = transform.get_forward();
    expected_dir = glm::normalize(target - transform.get_local_position());
    EXPECT_TRUE(vec3_approx_equal(forward, expected_dir, 0.01f));

    // Look at target above
    target = glm::vec3(0.0f, 10.0f, 0.0f);
    transform.look_at(target, glm::vec3(0.0f, 0.0f, 1.0f));
    forward = transform.get_forward();
    expected_dir = glm::normalize(target - transform.get_local_position());
    EXPECT_TRUE(vec3_approx_equal(forward, expected_dir, 0.01f));
}

// ==================== Matrix Tests ====================
TEST_F(TransformTest, WorldMatrix) {
    tmt::Entity entity = tmt::engine.ecs.create_entity();
    auto& transform = tmt::engine.ecs.add_component<tmt::Transform>(entity);

    // Set TRS values
    glm::vec3 pos(1.0f, 2.0f, 3.0f);
    glm::quat rot = glm::angleAxis(glm::radians(45.0f), glm::vec3(0.0f, 1.0f, 0.0f));
    glm::vec3 scale(2.0f, 3.0f, 4.0f);

    transform.set_local_position(pos);
    transform.set_local_rotation(rot);
    transform.set_local_scale(scale);

    // Get world matrix
    glm::mat4 world = transform.get_world_matrix();

    // Manually construct expected matrix
    glm::mat4 expected(1.0f);
    expected = glm::translate(expected, pos);
    expected = expected * glm::mat4_cast(rot);
    expected = glm::scale(expected, scale);

    // Compare matrices (element by element)
    for (int i = 0; i < 4; i++) {
        for (int j = 0; j < 4; j++) {
            EXPECT_TRUE(approx_equal(world[i][j], expected[i][j], 0.01f));
        }
    }
}

TEST_F(TransformTest, SetWorldMatrix) {
    tmt::Entity entity = tmt::engine.ecs.create_entity();
    auto& transform = tmt::engine.ecs.add_component<tmt::Transform>(entity);

    // Create a matrix manually
    glm::mat4 matrix(1.0f);
    matrix = glm::translate(matrix, glm::vec3(5.0f, 10.0f, 15.0f));
    matrix = glm::rotate(matrix, glm::radians(90.0f), glm::vec3(0.0f, 1.0f, 0.0f));
    matrix = glm::scale(matrix, glm::vec3(2.0f, 2.0f, 2.0f));

    // Set the world matrix
    transform.set_world_matrix(matrix);

    // Get it back and compare
    glm::mat4 result = transform.get_world_matrix();
    for (int i = 0; i < 4; i++) {
        for (int j = 0; j < 4; j++) {
            EXPECT_TRUE(approx_equal(result[i][j], matrix[i][j], 0.01f));
        }
    }
}

// ==================== Hierarchy Tests ====================
TEST_F(TransformTest, ParentChildHierarchy) {
    tmt::Entity parent_entity = tmt::engine.ecs.create_entity();
    tmt::Entity child_entity = tmt::engine.ecs.create_entity();

    auto& parent = tmt::engine.ecs.add_component<tmt::Transform>(parent_entity);
    auto& child = tmt::engine.ecs.add_component<tmt::Transform>(child_entity);

    // Initially no parent
    EXPECT_FALSE(child.has_parent());

    // Set parent
    child.set_parent(parent_entity);
    EXPECT_TRUE(child.has_parent());
    EXPECT_EQ(child.get_parent(), parent_entity);

    // Check parent's children list
    const auto& children = parent.get_children();
    EXPECT_EQ(children.size(), 1);
    EXPECT_EQ(children.count(child_entity), 1);

    // Clear parent
    child.clear_parent();
    EXPECT_FALSE(child.has_parent());
    EXPECT_TRUE(parent.get_children().empty());
}

TEST_F(TransformTest, MultiLevelHierarchy) {
    tmt::Entity grandparent_entity = tmt::engine.ecs.create_entity();
    tmt::Entity parent_entity = tmt::engine.ecs.create_entity();
    tmt::Entity child_entity = tmt::engine.ecs.create_entity();

    auto& grandparent = tmt::engine.ecs.add_component<tmt::Transform>(grandparent_entity);
    auto& parent = tmt::engine.ecs.add_component<tmt::Transform>(parent_entity);
    auto& child = tmt::engine.ecs.add_component<tmt::Transform>(child_entity);

    // Set up hierarchy: grandparent -> parent -> child
    parent.set_parent(grandparent_entity);
    child.set_parent(parent_entity);

    // Set positions
    grandparent.set_local_position(glm::vec3(10.0f, 0.0f, 0.0f));
    parent.set_local_position(glm::vec3(5.0f, 0.0f, 0.0f));
    child.set_local_position(glm::vec3(2.0f, 0.0f, 0.0f));

    // Check world positions
    EXPECT_TRUE(vec3_approx_equal(grandparent.get_world_position(), glm::vec3(10.0f, 0.0f, 0.0f)));
    EXPECT_TRUE(vec3_approx_equal(parent.get_world_position(), glm::vec3(15.0f, 0.0f, 0.0f)));
    EXPECT_TRUE(vec3_approx_equal(child.get_world_position(), glm::vec3(17.0f, 0.0f, 0.0f)));

    // Change grandparent position, should affect all
    grandparent.set_local_position(glm::vec3(0.0f, 0.0f, 0.0f));
    EXPECT_TRUE(vec3_approx_equal(parent.get_world_position(), glm::vec3(5.0f, 0.0f, 0.0f)));
    EXPECT_TRUE(vec3_approx_equal(child.get_world_position(), glm::vec3(7.0f, 0.0f, 0.0f)));
}

TEST_F(TransformTest, AddRemoveChildren) {
    tmt::Entity parent_entity = tmt::engine.ecs.create_entity();
    tmt::Entity child1_entity = tmt::engine.ecs.create_entity();
    tmt::Entity child2_entity = tmt::engine.ecs.create_entity();

    auto& parent = tmt::engine.ecs.add_component<tmt::Transform>(parent_entity);
    auto& child1 = tmt::engine.ecs.add_component<tmt::Transform>(child1_entity);
    auto& child2 = tmt::engine.ecs.add_component<tmt::Transform>(child2_entity);

    // Add children manually
    parent.add_child(child1_entity);
    parent.add_child(child2_entity);

    EXPECT_EQ(parent.get_children().size(), 2);
    EXPECT_EQ(parent.get_children().count(child1_entity), 1);
    EXPECT_EQ(parent.get_children().count(child2_entity), 1);

    // Remove one child
    parent.remove_child(child1_entity);
    EXPECT_EQ(parent.get_children().size(), 1);
    EXPECT_EQ(parent.get_children().count(child1_entity), 0);
    EXPECT_EQ(parent.get_children().count(child2_entity), 1);

    // Remove non-existent child (should not crash)
    parent.remove_child(child1_entity);
    EXPECT_EQ(parent.get_children().size(), 1);

    // Remove last child
    parent.remove_child(child2_entity);
    EXPECT_TRUE(parent.get_children().empty());
}

TEST_F(TransformTest, HierarchyWithRotation) {
    tmt::Entity parent_entity = tmt::engine.ecs.create_entity();
    tmt::Entity child_entity = tmt::engine.ecs.create_entity();

    auto& parent = tmt::engine.ecs.add_component<tmt::Transform>(parent_entity);
    auto& child = tmt::engine.ecs.add_component<tmt::Transform>(child_entity);

    child.set_parent(parent_entity);

    // Parent rotates 90 degrees around Y
    parent.set_local_rotation(glm::angleAxis(glm::radians(90.0f), glm::vec3(0.0f, 1.0f, 0.0f)));

    // Child at local position (10, 0, 0)
    child.set_local_position(glm::vec3(10.0f, 0.0f, 0.0f));

    // In world space, child should be at (0, 0, -10) due to parent rotation
    glm::vec3 world_pos = child.get_world_position();
    EXPECT_TRUE(vec3_approx_equal(world_pos, glm::vec3(0.0f, 0.0f, -10.0f), 0.01f));
}

TEST_F(TransformTest, HierarchyWithScale) {
    tmt::Entity parent_entity = tmt::engine.ecs.create_entity();
    tmt::Entity child_entity = tmt::engine.ecs.create_entity();

    auto& parent = tmt::engine.ecs.add_component<tmt::Transform>(parent_entity);
    auto& child = tmt::engine.ecs.add_component<tmt::Transform>(child_entity);

    child.set_parent(parent_entity);

    // Parent has scale of 2
    parent.set_local_scale(glm::vec3(2.0f));

    // Child has local scale of 3
    child.set_local_scale(glm::vec3(3.0f));

    // World scale should be 6 (2 * 3)
    glm::vec3 world_scale = child.get_world_scale();
    EXPECT_TRUE(vec3_approx_equal(world_scale, glm::vec3(6.0f), 0.01f));
}

// ==================== Edge Case Tests ====================
TEST_F(TransformTest, EdgeCaseZeroScale) {
    tmt::Entity entity = tmt::engine.ecs.create_entity();
    auto& transform = tmt::engine.ecs.add_component<tmt::Transform>(entity);

    transform.set_local_scale(glm::vec3(0.0f));

    // Should handle zero scale without crashing
    glm::mat4 matrix = transform.get_world_matrix();
    glm::vec3 world_scale = transform.get_world_scale();

    EXPECT_TRUE(vec3_approx_equal(world_scale, glm::vec3(0.0f)));
}

TEST_F(TransformTest, EdgeCaseVeryLargeValues) {
    tmt::Entity entity = tmt::engine.ecs.create_entity();
    auto& transform = tmt::engine.ecs.add_component<tmt::Transform>(entity);

    glm::vec3 large_pos(1000000.0f, 2000000.0f, 3000000.0f);
    transform.set_local_position(large_pos);

    EXPECT_TRUE(vec3_approx_equal(transform.get_local_position(), large_pos, 1.0f));

    // Matrix operations should still work
    glm::mat4 matrix = transform.get_world_matrix();
    EXPECT_TRUE(std::isfinite(matrix[0][0]));  // Check for NaN/Inf
}

TEST_F(TransformTest, EdgeCaseNegativeScale) {
    tmt::Entity entity = tmt::engine.ecs.create_entity();
    auto& transform = tmt::engine.ecs.add_component<tmt::Transform>(entity);

    // Negative scale (mirroring)
    glm::vec3 neg_scale(-1.0f, 2.0f, -3.0f);
    transform.set_local_scale(neg_scale);

    EXPECT_TRUE(vec3_approx_equal(transform.get_local_scale(), neg_scale));

    // Should still produce valid matrix
    glm::mat4 matrix = transform.get_world_matrix();
    glm::vec3 world_scale = transform.get_world_scale();

    // Verify it doesn't crash with negative scales
}

TEST_F(TransformTest, ComplexCombinedTransform) {
    tmt::Entity entity = tmt::engine.ecs.create_entity();
    auto& transform = tmt::engine.ecs.add_component<tmt::Transform>(entity);

    // Apply all types of transformations
    transform.set_local_position(glm::vec3(10.0f, 20.0f, 30.0f));
    transform.set_local_rotation(glm::angleAxis(glm::radians(45.0f), glm::normalize(glm::vec3(1.0f, 1.0f, 1.0f))));
    transform.set_local_scale(glm::vec3(2.0f, 3.0f, 4.0f));

    // Multiple operations
    transform.translate(glm::vec3(5.0f, 5.0f, 5.0f));
    transform.rotate_local(glm::vec3(0.0f, 1.0f, 0.0f), glm::radians(30.0f));
    transform.scale(glm::vec3(1.5f, 1.5f, 1.5f));

    // Verify everything is still valid
    glm::vec3 pos = transform.get_local_position();
    glm::quat rot = transform.get_local_rotation();
    glm::vec3 scale = transform.get_local_scale();
    glm::mat4 matrix = transform.get_world_matrix();

    EXPECT_FALSE(std::isnan(pos.x) || std::isnan(pos.y) || std::isnan(pos.z));
    EXPECT_FALSE(std::isnan(rot.w) || std::isnan(rot.x) || std::isnan(rot.y) || std::isnan(rot.z));
    EXPECT_FALSE(std::isnan(scale.x) || std::isnan(scale.y) || std::isnan(scale.z));
}